----------------------------------------------
------------MOD CODE -------------------------

KGL = SMODS.current_mod

sendDebugMessage("Launching Kiro's Game Logos Mod!", "KirosGameLogoMod")


SMODS.Atlas {key = "modicon",	path = "icon.png",	px = 32, py = 32}

KGL.logos ={
    {name = "Library of Ruina",
        file = "balatro.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("edd9b2"),
        secondaryColour = HEX("bfb8aa"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("362d28"),
        buttons_colour = HEX("362d28"),
        play_text = HEX("ba9350"),
        buttons_text = HEX("ba9350"),
        menu_colour = HEX("242221")},

    {name = "Limbus Company",
        file = "balatro2.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("6b0707"),
        secondaryColour = HEX("2e0b0b"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("ccbdb1"),
        buttons_colour = HEX("ccbdb1"),
        play_text = HEX("3d3834"),
        buttons_text = HEX("3d3834"),
        menu_colour = HEX("664933")},

    {name = "Lobotomy Corporation",
        file = "balatro3.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("dbd38a"),
        secondaryColour = HEX("b01510"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("141414"),
        buttons_colour = HEX("141414"),
        play_text = HEX("ff0000"),
        buttons_text = HEX("ebeb96"),
        menu_colour = HEX("ff0000")},

    {name = "Slender The Eight Pages",
        file = "balatro4.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("141414"),
        secondaryColour = HEX("141414"),
        contrast = 1,
        creditsColour = HEX("ffffff"),
        play_colour = HEX("141414"),
        buttons_colour = HEX("141414"),
        play_text = HEX("ffffff"),
        buttons_text = HEX("ffffff"),
        menu_colour = G.C.CLEAR},

    {name = "Half Life 1",
        file = "balatro5.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("994c0e"),
        secondaryColour = HEX("402b1a"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("666669"),
        buttons_colour = HEX("666669"),
        play_text = HEX("c9a128"),
        buttons_text = HEX("876e23"),
        menu_colour = HEX("414142")},

    {name = "Final Fantasy XIV: Shadowbringers",
        file = "balatro6.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("e8bf7d"),
        secondaryColour = HEX("431b69"),
        contrast = 2,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("36323d"),
        buttons_colour = HEX("36323d"),
        play_text = HEX("cc9650"),
        buttons_text = HEX("cc9650"),
        menu_colour = HEX("1a191c")},

    {name = "Z.A.T.O. I Love the World and Everything In It",
        file = "balatro7.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("362f27"),
        secondaryColour = HEX("523741"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("1c1c1c"),
        buttons_colour = HEX("1c1c1c"),
        play_text = HEX("e0e0e0"),
        buttons_text = HEX("e0e0e0"),
        menu_colour = HEX("592136")},

    {name = "Barotrauma",
        file = "balatro8.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("212124"),
        secondaryColour = HEX("30060e"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("ab8644"),
        buttons_colour = HEX("242423"),
        play_text = HEX("2e2e2d"),
        buttons_text = HEX("d4c5ab"),
        menu_colour = HEX("363534")},

    {name = "Yakuza",
        file = "balatro9.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("918e8f"),
        secondaryColour = HEX("636363"),
        contrast = 2,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("3b3b3b"),
        buttons_colour = HEX("3b3b3b"),
        play_text = HEX("b51919"),
        buttons_text = HEX("a6a294"),
        menu_colour = HEX("242323")},

    {name = "Kirby Triple Deluxe",
        file = "balatro10.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("e35dcd"),
        secondaryColour = HEX("a3125b"),
        contrast = 3,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("d4792a"),
        buttons_colour = HEX("d4792a"),
        play_text = HEX("ebdacc"),
        buttons_text = HEX("ebdacc"),
        menu_colour = HEX("98c5d6")},

    {name = "Dispatch",
        file = "balatro11.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("3f998e"),
        secondaryColour = HEX("284a46"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("b09e80"),
        buttons_colour = HEX("706655"),
        play_text = HEX("2e2e2e"),
        buttons_text = HEX("2e2e2e"),
        menu_colour = HEX("cccccc")},

    {name = "The Wolf Among Us",
        file = "balatro12.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("491a66"),
        secondaryColour = HEX("a519b5"),
        contrast = 2,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("6e1a2f"),
        buttons_colour = HEX("6e1a2f"),
        play_text = HEX("f2e6e9"),
        buttons_text = HEX("ba2065"),
        menu_colour = HEX("571c41")},

    {name = "Pikmin",
        file = "balatro13.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("5ed17b"),
        secondaryColour = HEX("e0eb98"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("6ab564"),
        buttons_colour = HEX("3f7a3b"),
        play_text = HEX("e0e0e0"),
        buttons_text = HEX("e0e0e0"),
        menu_colour = HEX("cccccc")},

    {name = "Halo",
        file = "balatro14.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("1a4f2d"),
        secondaryColour = HEX("b57e26"),
        contrast = 2,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("4d6b87"),
        buttons_colour = HEX("3d5266"),
        play_text = HEX("cccce0"),
        buttons_text = HEX("737373"),
        menu_colour = HEX("212a33")},

    {name = "Undertale",
        file = "balatro15.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("1c1c1c"),
        secondaryColour = HEX("1c1c1c"),
        contrast = 2,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("1c1c1c"),
        buttons_colour = HEX("1c1c1c"),
        play_text = HEX("d9c216"),
        buttons_text = HEX("e0e0e0"),
        menu_colour = HEX("cccccc")},

    {name = "Garrys Mod",
        file = "balatro16.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("81c3d4"),
        secondaryColour = HEX("81c3d4"),
        contrast = 2,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("369fbf"),
        buttons_colour = HEX("828282"),
        play_text = HEX("ffffff"),
        buttons_text = HEX("ffffff"),
        menu_colour = HEX("595959")},

    {name = "Silent Hill",
        file = "balatro17.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("d1d1d1"),
        secondaryColour = HEX("666464"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("374f9e"),
        buttons_colour = HEX("1a1a1a"),
        play_text = HEX("e0e0e0"),
        buttons_text = HEX("e0e0e0"),
        menu_colour = G.C.CLEAR},

    {name = "Judgement",
        file = "balatro18.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("454545"),
        secondaryColour = HEX("171717"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("a8b4b5"),
        buttons_colour = HEX("242424"),
        play_text = HEX("242424"),
        buttons_text = HEX("a8b4b5"),
        menu_colour = G.C.CLEAR},

    {name = "Jet Set Radio",
        file = "balatro19.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("e3dd3d"),
        secondaryColour = HEX("e36905"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("375c32"),
        buttons_colour = HEX("375c32"),
        play_text = HEX("d69c27"),
        buttons_text = HEX("d69c27"),
        menu_colour = HEX("739166")},

    {name = "Resident Evil - Original Trilogy",
        file = "balatro20.png",
        X = 255,
        Y = 100,
        credits = "Kiro",
        primaryColour = HEX("33201a"),
        secondaryColour = HEX("4a0c06"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("222eb3"),
        buttons_colour = HEX("222eb3"),
        play_text = HEX("e0e0e0"),
        buttons_text = HEX("e0e0e0"),
        menu_colour = HEX("737373")},

    {name = "Catherine",
        file = "balatro21.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("e346c1"),
        secondaryColour = HEX("eb83d4"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("d6d6d6"),
        buttons_colour = HEX("d6d6d6"),
        play_text = HEX("6e132b"),
        buttons_text = HEX("242424"),
        menu_colour = HEX("6e132b")},

    {name = "Deltarune",
        file = "balatro22.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("1c1c1c"),
        secondaryColour = HEX("20aafa"),
        contrast = 3,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("1c1c1c"),
        buttons_colour = HEX("1c1c1c"),
        play_text = HEX("e0e0e0"),
        buttons_text = HEX("e0e0e0"),
        menu_colour = HEX("e0e0e0")},

    {name = "DOOM",
        file = "balatro23.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("8c2306"),
        secondaryColour = HEX("d15524"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("292929"),
        buttons_colour = HEX("292929"),
        play_text = HEX("850909"),
        buttons_text = HEX("850909"),
        menu_colour = G.C.CLEAR},

    {name = "Minecraft",
        file = "balatro24.png",
        X = 272,
        Y = 55,
        credits = "Kiro",
        primaryColour = HEX("11d144"),
        secondaryColour = HEX("0a6e24"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("6e6e6e"),
        buttons_colour = HEX("6e6e6e"),
        play_text = HEX("e0e0e0"),
        buttons_text = HEX("e0e0e0"),
        menu_colour = HEX("3d2c22")},

    {name = "Left 4 Dead",
        file = "balatro25.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("05540a"),
        secondaryColour = HEX("068c0e"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("732222"),
        buttons_colour = HEX("525151"),
        play_text = HEX("e0e0e0"),
        buttons_text = HEX("e0e0e0"),
        menu_colour = HEX("141414")},

    {name = "Cyberpunk 2077",
        file = "balatro26.png",
        X = 283,
        Y = 77,
        credits = "Kiro",
        primaryColour = HEX("4f453d"),
        secondaryColour = HEX("36b8cf"),
        contrast = 3,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("7a1c1c"),
        buttons_colour = HEX("302220"),
        play_text = HEX("34a2ba"),
        buttons_text = HEX("34a2ba"),
        menu_colour = HEX("b53221")},

    {name = "Terraria",
        file = "balatro27.png",
        X = 220,
        Y = 71,
        credits = "Kiro",
        primaryColour = HEX("1d96e0"),
        secondaryColour = HEX("6338c7"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("6254d1"),
        buttons_colour = HEX("6254d1"),
        play_text = HEX("e0e0e0"),
        buttons_text = HEX("e0e0e0"),
        menu_colour = HEX("cccccc")},

    {name = "Super Balatro",
        file = "balatro28.png",
        X = 176,
        Y = 88,
        credits = "UltraEpicLeader100",
        primaryColour = HEX("8a83cc"),
        secondaryColour = HEX("8a83cc"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("d6bbb2"),
        buttons_colour = HEX("d6bbb2"),
        play_text = HEX("292929"),
        buttons_text = HEX("292929"),
        menu_colour = HEX("804522")},

    {name = "Sonic The Hedgehog",
        file = "balatro29.png",
        X = 227,
        Y = 42,
        credits = "UltraEpicLeader100",
        primaryColour = HEX("0e49a1"),
        secondaryColour = HEX("ba040d"),
        contrast = 3,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("d10808"),
        buttons_colour = HEX("d10808"),
        play_text = HEX("e0e0e0"),
        buttons_text = HEX("e0e0e0"),
        menu_colour = HEX("2634ad")},

    {name = "Gradius",
        file = "balatro30.png",
        X = 274,
        Y = 44,
        credits = "UltraEpicLeader100",
        primaryColour = HEX("000000"),
        secondaryColour = HEX("000000"),
        contrast = 1,
        creditsColour = HEX("2f74ba"),
        play_colour = HEX("000000"),
        buttons_colour = HEX("000000"),
        play_text = HEX("2f74ba"),
        buttons_text = HEX("2f74ba"),
        menu_colour = HEX("000000")},

    {name = "Persona 5",
        file = "balatro31.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("e60000"),
        secondaryColour = HEX("000000"),
        contrast = 3,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("1a1a1a"),
        buttons_colour = HEX("1a1a1a"),
        play_text = HEX("e0e0e0"),
        buttons_text = HEX("e0e0e0"),
        menu_colour = HEX("de0000")},

    {name = "Omori",
        file = "balatro32.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("f0ebeb"),
        secondaryColour = HEX("f0ebeb"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("292929"),
        buttons_colour = HEX("292929"),
        play_text = HEX("e0e0e0"),
        buttons_text = HEX("e0e0e0"),
        menu_colour = HEX("cccccc")},

    {name = "Oxenfree",
        file = "balatro33.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("1d382e"),
        secondaryColour = HEX("1a211e"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("731c36"),
        buttons_colour = HEX("731c36"),
        play_text = HEX("e0e0e0"),
        buttons_text = HEX("e0e0e0"),
        menu_colour = HEX("616161")},

    {name = "Phoenix Wright: Ace Attorney",
        file = "balatro34.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("124d99"),
        secondaryColour = HEX("8a0f40"),
        contrast = 2,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("6b9edb"),
        buttons_colour = HEX("6b9edb"),
        play_text = HEX("e0e0e0"),
        buttons_text = HEX("e0e0e0"),
        menu_colour = G.C.CLEAR},

    {name = "Resident Evil - Modern REmakes",
        file = "balatro35.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("27404f"),
        secondaryColour = HEX("363b3d"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("575757"),
        buttons_colour = HEX("575757"),
        play_text = HEX("e0e0e0"),
        buttons_text = HEX("e0e0e0"),
        menu_colour = HEX("292929")},

    {name = "Clair Obscur: Expedition 33",
        file = "balatro36.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("382828"),
        secondaryColour = HEX("261c1c"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("9e7f54"),
        buttons_colour = HEX("4d4843"),
        play_text = HEX("38332c"),
        buttons_text = HEX("e0e0e0"),
        menu_colour = G.C.CLEAR},

    {name = "Guilty Gear Xrd REV2",
        file = "balatro37.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("488752"),
        secondaryColour = HEX("1b361f"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("58b883"),
        buttons_colour = HEX("58b883"),
        play_text = HEX("e0e0e0"),
        buttons_text = HEX("e0e0e0"),
        menu_colour = HEX("616161")},

    {name = "Transistor",
        file = "balatro38.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("1d3d35"),
        secondaryColour = HEX("0e1211"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("222e2b"),
        buttons_colour = HEX("222e2b"),
        play_text = HEX("d4d4d4"),
        buttons_text = HEX("d4d4d4"),
        menu_colour = HEX("228574")},

    {name = "Milk Inside a Bag Of Milk Inside a Bag of Milk",
        file = "balatro39.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("000000"),
        secondaryColour = HEX("000000"),
        contrast = 1,
        creditsColour = HEX("7c128c"),
        play_colour = HEX("7c128c"),
        buttons_colour = HEX("7c128c"),
        play_text = HEX("e0e0e0"),
        buttons_text = HEX("e0e0e0"),
        menu_colour = HEX("000000")},

    {name = "Milk Outside a Bag Of Milk Outside a Bag of Milk",
        file = "balatro40.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("3d1919"),
        secondaryColour = HEX("0a0a0a"),
        contrast = 1,
        creditsColour = HEX("a32441"),
        play_colour = HEX("a32441"),
        buttons_colour = HEX("a32441"),
        play_text = HEX("e0e0e0"),
        buttons_text = HEX("e0e0e0"),
        menu_colour = HEX("262525")},
    
    {name = "Hitman",
        file = "balatro41.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("4f0a1a"),
        secondaryColour = HEX("42282e"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("bd0606"),
        buttons_colour = HEX("e6e6e6"),
        play_text = HEX("e0e0e0"),
        buttons_text = HEX("363636"),
        menu_colour = G.C.CLEAR},

    {name = "Hades",
        file = "balatro42.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("184a34"),
        secondaryColour = HEX("151a17"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("524545"),
        buttons_colour = HEX("524545"),
        play_text = HEX("b0abab"),
        buttons_text = HEX("b0abab"),
        menu_colour = HEX("99120b")},

    {name = "The Binding of Isaac",
        file = "balatro43.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("b09b80"),
        secondaryColour = HEX("1c1a1a"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("bdb2a6"),
        buttons_colour = HEX("bdb2a6"),
        play_text = HEX("3b3630"),
        buttons_text = HEX("3b3630"),
        menu_colour = HEX("787169")},

    {name = "Ball X Pit",
        file = "balatro44.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("4f0a1a"),
        secondaryColour = HEX("42282e"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("402a2a"),
        buttons_colour = HEX("402a2a"),
        play_text = HEX("c49595"),
        buttons_text = HEX("c49595"),
        menu_colour = HEX("c99a61")},

    {name = "Signalis",
        file = "balatro45.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("363433"),
        secondaryColour = HEX("363433"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("e0e0e0"),
        buttons_colour = HEX("d94141"),
        play_text = HEX("292626"),
        buttons_text = HEX("292626"),
        menu_colour = G.C.CLEAR},

    {name = "Baba is You",
        file = "balatro46.png",
        X = 333,
        Y = 216,
        credits = "MightyKingVideo",
        primaryColour = HEX("0f0f0f"),
        secondaryColour = HEX("0f0f0f"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("c22765"),
        buttons_colour = HEX("0f0f0f"),
        play_text = HEX("0f0f0f"),
        buttons_text = HEX("c22765"),
        menu_colour = G.C.CLEAR},

    {name = "New Super Mario Bros",
        file = "balatro47.png",
        X = 333,
        Y = 216,
        credits = "MightyKingVideo",
        primaryColour = HEX("6a8eb8"),
        secondaryColour = HEX("99b3d1"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("3ba357"),
        buttons_colour = HEX("237038"),
        play_text = HEX("f0f0f0"),
        buttons_text = HEX("cfcfcf"),
        menu_colour = HEX("cccfcd")},

    {name = "Among Us",
        file = "balatro48.png",
        X = 333,
        Y = 216,
        credits = "MightyKingVideo",
        primaryColour = HEX("121212"),
        secondaryColour = HEX("121212"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("44ab8c"),
        buttons_colour = HEX("3e6358"),
        play_text = HEX("232e2b"),
        buttons_text = HEX("bcd1cb"),
        menu_colour = HEX("333333")},

    {name = "Rhythm Heaven",
        file = "balatro49.png",
        X = 333,
        Y = 216,
        credits = "MightyKingVideo",
        primaryColour = HEX("70782c"),
        secondaryColour = HEX("786a2c"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("242424"),
        buttons_colour = HEX("242424"),
        play_text = HEX("b5552f"),
        buttons_text = HEX("d1a71d"),
        menu_colour = HEX("47c8d1")},

    {name = "Restitched",
        file = "balatro50.png",
        X = 312,
        Y = 112,
        credits = "LasagnaFelidae",
        primaryColour = HEX("319fd6"),
        secondaryColour = HEX("9c73d1"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("db1a95"),
        buttons_colour = HEX("db1a95"),
        play_text = HEX("e0e0e0"),
        buttons_text = HEX("e0e0e0"),
        menu_colour = G.C.CLEAR},

    {name = "LittleBigPlanet",
        file = "balatro51.png",
        X = 333,
        Y = 216,
        credits = "LasagnaFelidae",
        primaryColour = HEX("2d3742"),
        secondaryColour = HEX("161f29"),
        contrast = 2,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("4874ab"),
        buttons_colour = HEX("39445c"),
        play_text = HEX("c4c4c4"),
        buttons_text = HEX("c4c4c4"),
        menu_colour = G.C.CLEAR},

    {name = "Team Fortress 2",
        file = "balatro52.png",
        X = 333,
        Y = 216,
        credits = "MightyKingVideo",
        primaryColour = HEX("bab0a4"),
        secondaryColour = HEX("857f79"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("87776d"),
        buttons_colour = HEX("87776d"),
        play_text = HEX("d6cfba"),
        buttons_text = HEX("d6cfba"),
        menu_colour = HEX("4f4b46")},

    {name = "Pokémon",
        file = "balatro53.png",
        X = 333,
        Y = 216,
        credits = "MightyKingVideo",
        primaryColour = HEX("2a5791"),
        secondaryColour = HEX("2a8768"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("c7c9c9"),
        buttons_colour = HEX("9e9e9e"),
        play_text = HEX("ffffff"),
        buttons_text = HEX("ffffff"),
        menu_colour = HEX("61a8ab")},

    {name = "Doki Doki Literature Club",
        file = "balatro54.png",
        X = 333,
        Y = 216,
        credits = "MightyKingVideo",
        primaryColour = HEX("debaba"),
        secondaryColour = HEX("cfcfcf"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("752f52"),
        buttons_colour = HEX("752f52"),
        play_text = HEX("d9d2d5"),
        buttons_text = HEX("d9d2d5"),
        menu_colour = HEX("d1abbe")},

    {name = "Plants vs Zombies",
        file = "balatro55.png",
        X = 333,
        Y = 216,
        credits = "MightyKingVideo",
        primaryColour = HEX("6a8eb8"),
        secondaryColour = HEX("99b3d1"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("7d7c7c"),
        buttons_colour = HEX("7d7c7c"),
        play_text = HEX("121212"),
        buttons_text = HEX("121212"),
        menu_colour = HEX("545454")},

    {name = "Cult of the Lamb",
        file = "balatro56.png",
        X = 333,
        Y = 216,
        credits = "MightyKingVideo",
        primaryColour = HEX("e8e4cf"),
        secondaryColour = HEX("bdb49f"),
        contrast = 1,
        creditsColour = HEX("911624"),
        play_colour = HEX("911624"),
        buttons_colour = G.C.CLEAR,
        play_text = HEX("292626"),
        buttons_text = HEX("911624"),
        menu_colour = HEX("171717")},

    {name = "Earthbound",
        file = "balatro57.png",
        X = 152,
        Y = 68,
        credits = "UltraEpicLeader100",
        primaryColour = HEX("911649"),
        secondaryColour = HEX("b8a32e"),
        contrast = 2,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("89599e"),
        buttons_colour = HEX("89599e"),
        play_text = HEX("e3e3e3"),
        buttons_text = HEX("e3e3e3"),
        menu_colour = HEX("a3a3a3")},

    {name = "MOTHER",
        file = "balatro58.png",
        X = 183,
        Y = 68,
        credits = "UltraEpicLeader100",
        primaryColour = HEX("6b0d0d"),
        secondaryColour = HEX("1a1a1a"),
        contrast = 4,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("89599e"),
        buttons_colour = HEX("89599e"),
        play_text = HEX("e3e3e3"),
        buttons_text = HEX("e3e3e3"),
        menu_colour = HEX("a3a3a3")},
    
    {name = "Cuphead",
        file = "balatro59.png",
        X = 333,
        Y = 216,
        credits = "MightyKingVideo",
        primaryColour = HEX("ebc444"),
        secondaryColour = HEX("f0e2b4"),
        contrast = 1,
        creditsColour = HEX("383734"),
        play_colour = HEX("383734"),
        buttons_colour = HEX("383734"),
        play_text = HEX("b5ac8d"),
        buttons_text = HEX("b5ac8d"),
        menu_colour = HEX("b5ac8d")},

    {name = "Papers, Please",
        file = "balatro60.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("1c1c1c"),
        secondaryColour = HEX("1c1c1c"),
        contrast = 1,
        creditsColour = HEX("383734"),
        play_colour = HEX("6b5e42"),
        buttons_colour = HEX("6b5e42"),
        play_text = HEX("302525"),
        buttons_text = HEX("302525"),
        menu_colour = HEX("3d2f22")},

    {name = "The Seance of Blake Manor",
        file = "balatro61.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("1c1c1c"),
        secondaryColour = HEX("406385"),
        contrast = 1,
        creditsColour = HEX("cc9d25"),
        play_colour = HEX("cc9d25"),
        buttons_colour = HEX("1c1c1c"),
        play_text = HEX("1c1c1c"),
        buttons_text = HEX("cc9d25"),
        menu_colour = HEX("1c1c1c")},

    {name = "What Remains of Edith Finch",
        file = "balatro62.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("e3e2d5"),
        secondaryColour = HEX("e3e2d5"),
        contrast = 1,
        creditsColour = HEX("242422"),
        play_colour = HEX("242422"),
        buttons_colour = HEX("242422"),
        play_text = HEX("e3e2d5"),
        buttons_text = HEX("e3e2d5"),
        menu_colour = HEX("adab8b")},

    {name = "There is No Game",
        file = "balatro63.png",
        X = 333,
        Y = 216,
        credits = "UltraEpicLeader100",
        primaryColour = HEX("141414"),
        secondaryColour = HEX("141414"),
        contrast = 1,
        creditsColour = HEX("e3e3e3"),
        play_colour = HEX("4890bd"),
        buttons_colour = HEX("4890bd"),
        play_text = HEX("e3e3e3"),
        buttons_text = HEX("e3e3e3"),
        menu_colour = G.C.CLEAR},

    {name = "Metaphor: ReFantazio",
        file = "balatro64.png",
        X = 333,
        Y = 216,
        credits = "MightyKingVideo",
        primaryColour = HEX("535e55"),
        secondaryColour = HEX("a1a1a1"),
        contrast = 2,
        creditsColour = HEX("242422"),
        play_colour = HEX("bd1c47"),
        buttons_colour = HEX("696969"),
        play_text = HEX("262626"),
        buttons_text = HEX("e0e0e0"),
        menu_colour = G.C.CLEAR},

    {name = "Inscryption",
        file = "balatro65.png",
        X = 400,
        Y = 84,
        credits = "LasagnaFelidae",
        primaryColour = HEX("2d4541"),
        secondaryColour = HEX("2b2b2b"),
        contrast = 1,
        creditsColour = HEX("242422"),
        play_colour = HEX("232224"),
        buttons_colour = HEX("232224"),
        play_text = HEX("ba9b34"),
        buttons_text = HEX("ba9b34"),
        menu_colour = HEX("462e4a")},

    {name = "Concord",
        file = "balatro66.png",
        X = 333,
        Y = 216,
        credits = "MightyKingVideo",
        primaryColour = HEX("e3e2d5"),
        secondaryColour = HEX("e3e2d5"),
        contrast = 1,
        creditsColour = HEX("ba7627"),
        play_colour = HEX("a13f3f"),
        buttons_colour = HEX("a13f3f"),
        play_text = HEX("ba7627"),
        buttons_text = HEX("665847"),
        menu_colour = HEX("a13f3f")},

    {name = "Big Bird's Egg Catch",
        file = "balatro67.png",
        X = 112,
        Y = 32,
        credits = "UltraEpicLeader100",
        primaryColour = HEX("e3e2d5"),
        secondaryColour = HEX("e3e2d5"),
        contrast = 1,
        creditsColour = HEX("e0e0e0"),
        play_colour = HEX("242422"),
        buttons_colour = HEX("242422"),
        play_text = HEX("e0e0e0"),
        buttons_text = HEX("e0e0e0"),
        menu_colour = G.C.CLEAR},

    {name = "Persona 4",
        file = "balatro68.png",
        X = 333,
        Y = 216,
        credits = "MightyKingVideo",
        primaryColour = HEX("e8d52c"),
        secondaryColour = HEX("e8d94f"),
        contrast = 1,
        creditsColour = HEX("242422"),
        play_colour = HEX("e6db87"),
        buttons_colour = HEX("e6db87"),
        play_text = HEX("b58036"),
        buttons_text = HEX("b58036"),
        menu_colour = HEX("e8e8e8")},

    {name = "Persona 3",
        file = "balatro69.png",
        X = 333,
        Y = 216,
        credits = "MightyKingVideo",
        primaryColour = HEX("3177b0"),
        secondaryColour = HEX("456987"),
        contrast = 1,
        creditsColour = HEX("242422"),
        play_colour = HEX("303e4a"),
        buttons_colour = HEX("4c708f"),
        play_text = HEX("adadad"),
        buttons_text = HEX("333333"),
        menu_colour = HEX("4784c9")},

    {name = "Lies of P",
        file = "balatro70.png",
        X = 333,
        Y = 216,
        credits = "Kiro",
        primaryColour = HEX("e3e2d5"),
        secondaryColour = HEX("e3e2d5"),
        contrast = 1,
        creditsColour = HEX("c21f1f"),
        play_colour = HEX("404040"),
        buttons_colour = HEX("404040"),
        play_text = HEX("c21f1f"),
        buttons_text = HEX("bdbdbd"),
        menu_colour = HEX("141414")},
    
}



--------------------
-- Config Options --
--------------------
---

function G.FUNCS.selected_main_logo(arg)
    KGL.config.selected_logo = arg.to_key
    SMODS.save_mod_config(KGL)
end


   local ordered_names, viewed_logo = {}, 1
  for k, v in ipairs(KGL.logos) do
    ordered_names[#ordered_names+1] = v.name
--    if v.name == G.GAME.viewed_back.name then viewed_logo = k end
  end

KGL.config_tab = function()
    return {n=G.UIT.ROOT, config = {align = "cm", padding = 0.05, colour = G.C.CLEAR}, nodes={
        create_toggle({label = "Enable fixed logo (requires restart)", ref_table = KGL.config, ref_value = "enable_fixed_logo"}),
        create_option_cycle({
                align = "cm",
                ref_table = KGL.config,
                ref_value = "selected_logo",
                current_option = KGL.config.selected_logo,
                opt_callback = "selected_main_logo",
                w = 10,
                label = "Selected Logo",
                options = ordered_names,
            }),
    }}
end

local selectedMenuRandom = math.random(1,70)

local selectedMenuFixed = KGL.config.selected_logo or 1

KGL.selected_logo = {name = "AAAA", credits = "AAAA", primaryColour = "AAAA", secondaryColour = "AAAA", contrast = "AAAA", creditsColour = "AAAA"}



local selectedMenu
if KGL.config.enable_fixed_logo == false then
    selectedMenu = selectedMenuRandom
else
    selectedMenu = selectedMenuFixed
end
    KGL.selected_music = selectedMenu or 1
    KGL.selected_logo.name = KGL.logos[selectedMenu].name
    KGL.selected_logo.file = KGL.logos[selectedMenu].file
    KGL.selected_logo.X = KGL.logos[selectedMenu].X
    KGL.selected_logo.Y = KGL.logos[selectedMenu].Y
    KGL.selected_logo.credits = KGL.logos[selectedMenu].credits
    KGL.selected_logo.primaryColour = KGL.logos[selectedMenu].primaryColour
    KGL.selected_logo.secondaryColour = KGL.logos[selectedMenu].secondaryColour
    KGL.selected_logo.contrast = KGL.logos[selectedMenu].contrast
    KGL.selected_logo.creditsColour = KGL.logos[selectedMenu].creditsColour
    KGL.selected_logo.play_colour = KGL.logos[selectedMenu].play_colour
    KGL.selected_logo.buttons_colour = KGL.logos[selectedMenu].buttons_colour
    KGL.selected_logo.play_text = KGL.logos[selectedMenu].play_text
    KGL.selected_logo.buttons_text = KGL.logos[selectedMenu].buttons_text
    KGL.selected_logo.menu_colour = KGL.logos[selectedMenu].menu_colour
    SMODS.Atlas{key = "balatro", path = KGL.selected_logo.file, px = KGL.selected_logo.X, py = KGL.selected_logo.Y, prefix_config = { key = false }}


